# Generated by Django 6.1.1 on 2026-09-11 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '01. Department',
                'verbose_name_plural': '01. Department',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('item_type', models.CharField(choices=[('RAW', 'Raw Material'), ('FINISHED', 'Finished Good')], max_length=10)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': '04. Item',
                'verbose_name_plural': '04. Item',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('machine_code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Under Maintenance'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
            ],
            options={
                'verbose_name': '05. Machine',
                'verbose_name_plural': '05. Machine',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': '03. Supplier',
                'verbose_name_plural': '03. Supplier',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Production Manager'), ('SUPERVISOR', 'Floor Supervisor'), ('MACHINE_OPERATOR', 'Worker'), ('INVENTORY_CLERK', 'Store Keeper'), ('WAREHOUSE_HEAD', 'Store Manager'), ('QUALITY_MANAGER', 'Quality Manager'), ('QUALITY_INSPECTOR', 'Quality Inspector'), ('PROCUREMENT', 'Purchase Manager'), ('MAINTENANCE_ENGINEER', 'Technician'), ('SALES_EXECUTIVE', 'Sales Executive'), ('DISPATCH_COORDINATOR', 'Dispatch Coordinator'), ('HR_EXECUTIVE', 'HR Executive')], max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '02. Employee',
                'verbose_name_plural': '02. Employee',
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=2, max_digits=10)),
                ('finished_good', models.ForeignKey(limit_choices_to={'item_type': 'FINISHED'}, on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='backend.item')),
                ('raw_material', models.ForeignKey(limit_choices_to={'item_type': 'RAW'}, on_delete=django.db.models.deletion.CASCADE, to='backend.item')),
            ],
            options={
                'verbose_name': '06. Bill of Materials',
                'verbose_name_plural': '06. Bill of Materials',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('quantity_to_build', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('QC_PENDING', 'QC Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assigned_machine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.machine')),
                ('product_to_build', models.ForeignKey(limit_choices_to={'item_type': 'FINISHED'}, on_delete=django.db.models.deletion.CASCADE, to='backend.item')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.employee')),
            ],
            options={
                'verbose_name': '07. Production Order',
                'verbose_name_plural': '07. Production Orders',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.supplier'),
        ),
    ]
